
#### `chatbot-system/docker-compose.yml`
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: chatbot_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: streamlit run app/main.py --server.port 8501 --server.address 0.0.0.0
    